### ISSUE TITLE
getData returns nothing

### ISSUE THREAD

**Issue by pattyland** [stevendwood/html5-dropzone#4]
Hi! I just started to use this library and have problems retrieving data. I use `draggable("#id").setData("text/x-test", "Hello world")` and it works great with different drop zones. But when I call `e.dataTransfer.getData("x-test")` in the function that handles drop, it returns only empty strings.
And idea what I could do wrong?

I rebuild the example from the Readme at JSFiddle: https://jsfiddle.net/pattyland/n1qrkzuy/
Same behaviour

Greets, Sören

**Comment by stevendwood** [comment]
Hi - yeah you need to use the full key to get the data - so not just getData("x-test") but getData("text/x-test");

https://jsfiddle.net/n1qrkzuy/1/

**Comment by pattyland** [comment]
Thank you! I created a pull request to change the example in the readme, I guess this till help others!
